### ISSUE TITLE
[WEC-Sim Applications]Definition of area in quadratic drag coefficient

### ISSUE THREAD

**Issue by hachikoi1** [WEC-Sim/WEC-Sim#1051]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Cite the [WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications) case in question**
_Please identify the WEC-Sim applications case in question._
Dear all,
I am comparing the hydrodynamic results between WEC-Sim and OpenFAST-HydroDyn, but some differences appear in quadratic drag.

**Describe the bug or issue**
_A clear and concise description of what the perceived bug or issue is._
In HydroDyn, the calculation reference point is on the MSL, and the quadratic drag coefficient matrix (https://github.com/IEAWindTask37/IEA-15-240-RWT/blob/master/OpenFAST/IEA-15-240-RWT-UMaineSemi/IEA-15-240-RWT-UMaineSemi_HydroDyn.dat) is 
9.23E+05    0.00E+00    0.00E+00    0.00E+00    -8.92E+06   0.00E+00 
0.00E+00    9.23E+05    0.00E+00    8.92E+06    0.00E+00    0.00E+00
0.00E+00    0.00E+00    2.30E+06    0.00E+00    0.00E+00    0.00E+00
0.00E+00    8.92E+06    0.00E+00    1.68E+10    0.00E+00    0.00E+00
-8.92E+06   0.00E+00    0.00E+00    0.00E+00    1.68E+10    0.00E+00
0.00E+00    0.00E+00    0.00E+00    0.00E+00    0.00E+00    4.80E+10
Question 1: I am confused about the results, especially for the non-zero values of (1,5),(2,4)(5,1),(4,2). Could anyone tell me how to calculate these values?
Question 2: Does the quadratic drag coefficient matrix have a reference point? The coefficient matrices between COG and the reference point on the MSL should be different, but quadratic drag coefficient = 0.5CdRhoA seems to to be independent of the reference point.
Question3: What's the meaning of area A in 0.5CdRhoA, especially for the A in roll, pitch and yaw directions?
The studied floating platform is shown below.
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/3fa0c64a-0810-4b5d-9751-ee1cb5a77465)
![image](https://github.com/WEC-Sim/WEC-Sim/assets/106663159/be368650-96c3-4f89-aa54-0f591742088a)

**To Reproduce**
_Steps to reproduce the behavior:_

1. _Go to '...'_
1. _Click on '....'_
1. _Scroll down to '....'_
1. _See error_

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
_If applicable, add screenshots to help explain your problem. For example, a screen shot of the exact error message from the MATLAB command line._

**Workstation Information (this section MUST BE completed):**
 - OS: [e.g. iOS8.1, Windows 10, Linux 5.12.1]
 - [MATLAB/Simulink Release](https://www.mathworks.com/help/matlab/release-notes.html) [2019b, 2020a, 2020b, 2021a]
 - [WEC-Sim Release](http://wec-sim.github.io/WEC-Sim/man/release_notes.html) [v3.1, v4.0, v4.1]

**Additional context**
_Add any other context about the problem here._

**Comment by dforbush2** [comment]
Hi @hachikoi1 

I'm sort of confused where exactly the WEC-Sim question is here, and I am not familiar with HydroDyn, but I will try and talk through your questions.

1). The physical meaning of the off-diagonal coefficients is a drag-like force that is induced through cross-coupling between the motions. In this case term (1,5) would be the "drag force" in pitch that occurs as a result of surge motion (i.e., because this is negative, forcing a body to have a surge velocity will contribute a "drag force" that will encourage the body to pitch. This is probably because, as you note, these are defined at the MSL, so a surge drag force is likely exerting a non-zero pitch moment on the body, and this term is capturing that) Again I'm not familiar with HydroDyn, but this is my interpretation. 

In general drag coefficients in oscillating flow cannot be calculated cleanly from analytical solution and can be shown to depend strongly on the Keulegan-Carpenter number, which relates amplitude and period of oscillation to the bodies' characteristic length. Unless there are experimental or high-fidelity results to pull from, these are usually used as tuning parameters in a WEC-Sim model.

2). With respect to coordinate systems, check out the implementation in the WEC-Sim body block. The velocity that multiplies the user-specified drag terms (Cd, A) is the velocity defined at the body COG. For diagonal translational modes, this will be identical between the coordinate systems. The diagonal rotational modes and the off-diagonal terms will all be different because by changing the presumed axis of rotation, the location at which the drag force can be thought to act will also change. For simple geometries, the diagonal terms can be related analytically by the parallel axis theorem and integration.

3). As noted in 1), the Area for drag bodies in oscillating flow is not well-defined. A good first approximation is to think about the (linearized for small motions) area that will be pushing the water if a rotation about the specified axis occurs. But much like Cd, this can be reasonably treated as a tuning parameter. For example https://ieeexplore.ieee.org/document/8094941

**Comment by hachikoi1** [comment]
> [dforbush2](/dforbush2)

Dear [dforbush2](https://github.com/dforbush2)
Thank you very much for your reply.
I was confused about the calculation of the quadratic drag coefficient, but I got the answer from you. 
Theoretically, we can get quadratic drag and velocity at COG based on the the quadratic drag, displacement and velocity at PRP. By solving the equation system of F_{quaddragCOG} = -0.5CdrhoAv_Cog|v_Cog| at each time step, we can ontain quadratic drag coefficient at COG. 
I found that WEC-Sim is not able to handle the non-diagonal fit terms. Thus, related codes are:
```
Q11 = zeros(length(OpenFASTOutputs(:,1)),1);
Q22 = Q11;
Q33 = Q11;
Q44 = Q11;
Q55 = Q11;
Q66 = Q11;
for j = 1:length(OpenFASTOutputs(:,1))
    Q11(j) = -COGQuadDrag(j,1)/(abs(COGVel(j,1))*COGVel(j,1));
    Q22(j) = -COGQuadDrag(j,2)/(abs(COGVel(j,2))*COGVel(j,2));
    Q33(j) = -COGQuadDrag(j,3)/(abs(COGVel(j,3))*COGVel(j,3));
    Q44(j) = -COGQuadDrag(j,4)/(abs(COGVel(j,4))*COGVel(j,4));
    Q55(j) = -COGQuadDrag(j,5)/(abs(COGVel(j,5))*COGVel(j,5));
    Q66(j) = -COGQuadDrag(j,6)/(abs(COGVel(j,6))*COGVel(j,6));
end
COGQuadDragCoeff3 = [mean(Q11(2:end)) 0 0 0 0 0;
                     0 mean(Q22(2:end)) 0 0 0 0;
                     0 0 mean(Q33(2:end)) 0 0 0;
                     0 0 0 mean(Q44(2:end)) 0 0;
                     0 0 0 0 mean(Q55(2:end)) 0;
                     0 0 0 0 0 mean(Q66(2:end))];
```
Unfortunately, the resulting coefficient matrix at COG obtained at each time step is different. For example, the Q11 results at the first ten time step are
62178806.5411955
67140092.5727549
73358758.8438859
85036297.2631157
105098510.644515
142646344.848903
225031740.397949
474107399.124731
2264133594.48800
-13343387645.4975
Q33 results at the first ten time step are
8728844.43833093
10662998.1085941
11317353.3910709
13239035.1559764
17160801.0458012
27435741.5191107
80450679.6279351
-1667776888.12429
-11280066.9452040
-847055.142940493
Similarly, I introduced the (1, 5) term, but the results are equally unsatisfactory
```
Q11 = zeros(length(OpenFASTOutputs(:,1)),1);
Q33 = Q11;
Q44 = Q11;
Q66 = Q11;
Q15 = Q11;
for j = 1:length(OpenFASTOutputs(:,1))
    Q33(j) = -COGQuadDrag(j,3)/(abs(COGVel(j,3))*COGVel(j,3));
    Q66(j) = -COGQuadDrag(j,6)/(abs(COGVel(j,6))*COGVel(j,6));
    AbsVV  =  [abs(COGVel(j,1))*COGVel(j,1)  abs(COGVel(j,5))*COGVel(j,5) 0;
               abs(COGVel(j,2))*COGVel(j,2) -abs(COGVel(j,4))*COGVel(j,4) 0;
               0 -abs(COGVel(j,2))*COGVel(j,2) abs(COGVel(j,4))*COGVel(j,4)];
    F      = -COGQuadDrag(j,[1 2 4])';
    x      =  linsolve(AbsVV,F);
    Q11(j) =  x(1);
    Q15(j) =  x(2);
    Q44(j) =  x(3);
end
COGQuadDragCoeff3 = [mean(Q11(2:end)) 0 0 0 mean(Q15(2:end)) 0;
                     0 mean(Q11(2:end)) 0 -mean(Q15(2:end)) 0 0;
                     0 0 mean(Q33(2:end)) 0 0 0;
                     0 -mean(Q15(2:end)) 0 mean(Q44(2:end)) 0 0;
                     mean(Q15(2:end)) 0 0 0 mean(Q44(2:end)) 0;
                     0 0 0 0 0 mean(Q66(2:end))];
```
Could you give me some advice?

Best Regards,

**Comment by dforbush2** [comment]
Looks like you are very much on the right track with this. There is a project related to a very similar geometry, and this was a struggle for everyone. What you are trying to do is difficult!

https://www.nrel.gov/docs/fy20osti/76210.pdf

If you have a time series of reference data, I would recommend you use WEC-Sim within an optimization loop and use something like 'fminsearch' to tune your drag coefficients or areas post-hoc. I can provide some example code if this would be helpful. Generally I start using wecSimMCR 

http://wec-sim.github.io/WEC-Sim/master/user/advanced_features.html#multiple-condition-runs-mcr

to do a coarse grid-search and then use the best-performing set as the initial guess for the optimizer.

**Comment by dforbush2** [comment]
With that in mind, I will explore expanding the drag coefficients to use a full matrix rather than just a diagonal. If you need to break the library body block to modify this calculation to simplify your drag term definition it should be a relatively simple change.

**Comment by hachikoi1** [comment]
> If you have a time series of reference data, I would recommend you use WEC-Sim within an optimization loop and use something like 'fminsearch' to tune your drag coefficients or areas post-hoc. I can provide some example code if this would be helpful. Generally I start using wecSimMCR

Dear [dforbush2](https://github.com/dforbush2)
Thanks very much for your reply. I will test this approach.

Best regards,

**Comment by dforbush2** [comment]
Hi @hachikoi1 

It is possible to instead specify body.quadDrag.drag as a 6 x 6  matrix.

See lines 327 to 331 of bodyClass.m for how this works with Cd and A...basically if you specify body.quadDrag.drag, it will use this directly instead of 0.5 * rho * A * Cd. This may be the fastest way to get what you want directly. 

Ultimately, the field that is utilized in simulation is body.hydroForce.quadDrag.
