### ISSUE TITLE
[Theory or Implementation] CG location of the example sphere

### ISSUE THREAD

**Issue by yman95** [WEC-Sim/WEC-Sim#1068]
Hi sorry to ask about CG again

**Is your question request related to a problem? Please describe.**
I'm trying to compare the BEM results from mine to the sphere example in \example\BEMIO\NEMOH. The example geometry \Mesh\Nemoh.dat is the submerged part of a sphere with radius 5, but its CG is located at (0,0,-2). It seems like it is the CG of the submerged part only and not the entire sphere. (The black boxes in figures show CG)
Example geometry:
![image](https://github.com/WEC-Sim/WEC-Sim/assets/16159470/ca21a012-e8e5-412f-8b86-f234b52695c4)

When I entered the example sphere's mass and use archimedes function, I get the exact same center of buoyancy but my CG is at the sphere's geometric center. 
![image](https://github.com/WEC-Sim/WEC-Sim/assets/16159470/3cbe8876-7e1d-4f3d-affc-86fc3e8e7dab)
Submerged part:
![image](https://github.com/WEC-Sim/WEC-Sim/assets/16159470/6f4f2cf7-e620-4996-bb43-d0160faa4013)

So should the CG be done about the entire geometry or just the submerged part? Thanks.

**Describe the theory or implementation approach that you have a question**
Since the BEM calculations are to be done about CG, so I figure it's important to understand where CG should be. 

**Describe the type of conclusion or resolution you are looking for**
Understanding the location of CG

Thanks for the support,
Yi

**Comment by dforbush2** [comment]
Hi @yman95 

The origin of the BEM run should be at the CG of the whole body and the BEM mesh file should contain only the submerged geometry. Because the origin _must_ be at the CG of the body, we specify the offset between the body (0,0,0 at CG) and global coordinate system in the input file, in this case, (0,0,2). 

If you look at the WAMIT or CAPYTAINE versions of this example, you will see a mesh position offset by +0,0,2, which makes sense in this context. It seems that this is intended to model either a case where a hemisphere is the total geometry (and thus has a CG at 3*radius/8...perhaps approximated as 2 here?) or a sphere with a non-uniform internal mass distribution resulting in a CG below that which would be predicted purely from geometry. 

As you point out, however, the NEMOH example is different. 

To be honest I have not run NEMOH in so long I forget if its coordinate system definition differs from WAMIT, but it is possible you have identified a bug here. I will follow up soon.

**Comment by yman95** [comment]
Understood, thanks. So, it was because the mass of the geometry was not uniformly distributed (bottom heavy), such that the CG is located at a lower place. Also, NEMOH has different coordinates convention than other software. It was confusing to me but now I get it.

I was able to get similar results using my mesh with the same parameters with minor spike differences, for example the normalized excitation force magnitude for the cylinder example.
WEC-Sim example result:
![Excitation_Magnitude](https://github.com/WEC-Sim/WEC-Sim/assets/16159470/e39825bf-67b7-4215-858e-5c7ed79b94ec)

my result:
![Excitation_Magnitude](https://github.com/WEC-Sim/WEC-Sim/assets/16159470/a77c2e75-61d0-413c-9a04-20280cf135b3)

WEC-Sim example result:
![Radiation_Damping](https://github.com/WEC-Sim/WEC-Sim/assets/16159470/b6073b4e-2e07-4a91-bb53-fb46479afc66)

my result:
![Radiation_Damping](https://github.com/WEC-Sim/WEC-Sim/assets/16159470/68a8ada4-0319-45fc-907b-2e0a8cb64e58)



Am I correct to assume that those are because mesh differences?
WEC-Sim mesh (regular rectangles): 
![image](https://github.com/WEC-Sim/WEC-Sim/assets/16159470/67962405-8fd2-44db-adb5-b3e72696a1a2)

my mesh (from FreeCAD, triangular):
![image](https://github.com/WEC-Sim/WEC-Sim/assets/16159470/2ee35f48-dede-4fb5-900f-4785403ff5f8)

**Comment by dforbush2** [comment]
Hi @yman95 

Your results look great. It's hard to say exactly where the minor differences come from, but its probable, as you suggest, that this is a mesh difference. 

This sphere example was from an IEA OES testing campaign and represents an actual physical device that was tested, so the CG that is not at the geometric center is intentional and is representative of the tested device.
