### ISSUE TITLE
Request for Assistance with WEC-Sim Installation in MATLAB for an AI Project

### ISSUE THREAD

**Issue by Khalid-1994-06-17** [WEC-Sim/WEC-Sim#1145]
My name is Khalid Al Nahyan, and I am a student at Mohammed Bin Zayed University for Artificial Intelligence. I am currently working on a project for my Foundations and Advanced Topics in Machine Learning course, which involves using reinforcement learning to control FPTO.
 
To facilitate this, I am planning on using the WEC-Sim files, which I understand is an area of your expertise. However, I am encountering some difficulties with installing WEC-Sim into MATLAB. I have attempted to troubleshoot these issues, but it appears I need some further assistance. 
 
If it would be possible for you or perhaps someone on your team to assist me with this, I would be immensely grateful. I believe a guided installation and testing of the package would be most beneficial and ensure that I am utilizing the tool correctly. 
 
If you are amenable, could we perhaps schedule an online meeting at your earliest convenience? I am confident that your assistance would greatly contribute to the success of my project. 
 
 Thank you very much for your time and consideration. I look forward to possibly hearing from you soon.

I am on the part where I typed wecSim in the comand window, it gave an error: Error using initializeWecSim
This is not the correct *.h5 file. Please install
git-lfs to access the correct *.h5 file, or run
\hydroData\bemio.m to generate a new *.h5 file

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in wecSim (line 43)
run('initializeWecSim'); how could I fix it I ran the bemio.m and got figures (6)

**Comment by dav-og** [comment]
Hello @Khalid-1994-06-17,

For future reference, we ask that users fill in one of our issue templates in order to help us help you. If you hit 'New issue' on the top right here:

![image](https://github.com/WEC-Sim/WEC-Sim/assets/12831266/a85dbdd2-5ce6-4ea4-92b6-f732414c30d5)

Then you'll see several different options for issue templates:

![image](https://github.com/WEC-Sim/WEC-Sim/assets/12831266/ca419e49-81b8-43da-a4be-ca285dd2f098)

Please fill in the most appropriate template for your issue.

In general, we try to provide good documentation and YouTube videos so that users can get started on their own, with minimal assistance. If you're struggling to get started, I recommend following some of the YouTube tutorials, e.g.: https://youtu.be/SUA_6Nd1w9g

Based on your output, it looks like you've managed to install WEC-Sim, but you haven't run the bemio.m script in the hydroData folder, hence you're missing the necessary .h5 file.

I'll close out this issue for now - if you continue to struggle running the code, please fill in an issue template.

If you'd like to work more closely with the WEC-Sim team and set up a formal collaboration, please check out the TEAMER program: https://teamer-us.org/
