### ISSUE TITLE
Understanding the Calculation of Characteristic Mass in Wave Energy Converter Simulations

### ISSUE THREAD

**Issue by shariful-info** [WEC-Sim/WEC-Sim#1269]
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Is your question request related to a problem? Please describe.**
I am working on simulations of Wave Energy Converters (WEC) using WECSim. While reading the paper "DEVELOPMENT AND DEMONSTRATION OF THE WEC-SIM WAVE ENERGY CONVERTER SIMULATION TOOL" by Yi-Hsiang Yu, Michael Lawson, Kelley Ruehl, and Carlos Michelen (2014) ([Link](https://vtechworks.lib.vt.edu/server/api/core/bitstreams/12bdad26-05cc-45aa-8164-0da3aeac4d79/content)), I noticed that it compares results with another paper, "Numerical benchmarking study of a selection of wave energy converters" by Babarit, A., Hals, J., Muliawan, M.J., Kurniawan, A., Moan, T., and Krokstad, J. (2012) ([Link](https://doi.org/10.1016/j.renene.2011.10.002)). In this second paper, the term "characteristic mass" is used. However, I am having difficulty understanding how it is calculated.

**Describe the theory or implementation approach that you have a question**
The term "characteristic mass" is mentioned in various summary sheets for different types of WECs in the paper "Numerical benchmarking study of a selection of wave energy converters." Despite this reference, I am unclear on the specific methodology for calculating the characteristic mass.

**Personal project context**
In my project, I aim to simulate the behavior of WECs, and find out the power. I need to ensure that my simulations are as accurate and reliable as possible.

**Describe the type of conclusion or resolution you are looking for**
I am looking for a detailed explanation of how to calculate characteristic mass, including any relevant equations or methodologies. If possible, pointers to documentation, code, or additional resources that provide further information on this concept would be greatly appreciated.

**Additional context**
Figure 15 from the first paper (Yu et al.) showing the comparison with the Babarit et al. paper:
![image](https://github.com/WEC-Sim/WEC-Sim/assets/104794958/86bd7538-5067-4014-99cf-591586b1e827)

**Comment by kmruehl** [comment]
@shariful-info Thank you for your question. If you're interested in the masses used for the WEC-Sim simulations in Yu 2014, those are included in the publication in Tables 1-3. However, I believe your question more about how the characteristic mass is calculated in Babarit 2012.

According to Babarit 2012, "characteristic mass has been taken to include the mass of foundations for devices that find their force-reference in the sea bottom. For self-referencing floating systems, the mooring layout has not been included in the analysis, but the characteristic mass is set equal to (1.15 +/- 0.1) times the displaced mass in order to roughly account for the mooring system, although this may be very uncertain. For the characteristic wetted surface area, foundations are included in the same way, but no additional surface area has been attributed to mooring systems." 

I recommend reaching out to the authors of Babarit 2012 to ask about how they determined the characteristic mass for each WEC, listed in Figures 12-19. However, my understanding is that the authors are using characteristic mass similar to the use of [characteristic length](https://www.sciencedirect.com/topics/mathematics/characteristic-length) in hydrodynamics. It is used to generally quantify the mass of the WEC, which could include mooring, foundation, etc. 

Thanks again
