### ISSUE TITLE
[Developer Issue] BEMIO warning soon to be an error

### ISSUE THREAD

**Issue by kmruehl** [WEC-Sim/WEC-Sim#1305]
**MATLAB Version**
2024a

**Describe the issue**
BEMIO is currently throwing warnings when parsing BEM output files. This will become an error in the future and needs to be resolved. This warning is from WAMIT, but the same issue happens for all read BEM scripts. 

``` matlab
Warning: Colon operands must be real scalars. This warning will become an error in a
future release. 
> In readWAMIT (line 102)
In bemio (line 3)
```

**Comment by akeeste** [comment]
I tested this out briefly because I was initially worried that something was happening to the "end" index (this is not the case). This is what I found in some initial testing:

The colon is utilized to create a set of indices between two values. What's happening in ``readWAMIT`` is essentially that an array of indices is combined with the colon, making the starting point of the set ambiguous. Previously MATLAB defaulted to the first point in that array but in the future it will throw an error. 

i.e. in readWAMIT line 102:
`tmp = textscan(raw{n}(find(raw{n}=='=')+1:end),'%f');`

The string ``raw{n}`` has two equals signs, so ``find(raw{n}=='=')`` gives e.g. ``[20 59]``
``raw{n}`` is then indexed like: ``raw{n}([20 59] : end)``. This indexing is ambiguous and could result in either ``20:end`` or ``59:end``

We'll have to go through these cases and identify which index we should be using--likely whatever was the default behavior was previously
