### ISSUE TITLE
[WEC-Sim Applications] Translation to rotation with rack and pinion

### ISSUE THREAD

**Issue by laucrom** [WEC-Sim/WEC-Sim#1308]
**Describe the bug or issue**
I am trying to simulate a heaving point absorber WEC, with a PTO consisting of a rack and pinion mechanism converting the heave motion to a rotation for the rotary generator. My main interest is including the additional (rotational) inertia the rack and pinion introduces in the system. However, so far I haven't found a way to implement the conversion from heave to rotation in WEC-Sim. 
Is there a way to do this? 
I've also tried including the additional inertia as an equivalent mass but this affects the hydrodynamics of the WEC and that's not what I'm after.

**To Reproduce**
N/A

**Expected behavior**
N/A
**Screenshots**
N/A

**Workstation Information (this section MUST BE completed):**
 - OS: Windows 10
 - MATLAB/Simulink Release: R2023b
 - WEC-Sim Release: v6.0

**Additional context**
N/A

**Comment by jleonqu** [comment]
Hello @laucrom 
We don’t have a specific block in WEC-Sim for linear-to-rotational motion conversion, the motion conversion blocks that we have are for rotational-to-linear motion. You will need to create a subsystem for your specific application. I suggest to edit the RM3_cHydraulic_PTO.slx example to represent your system, that example is available here in this [link](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/main/PTO-Sim/RM3/RM3_cHydraulic_PTO). You can take the velocity output from the response and use that as your input for your system. The output should be the force in the rack mechanism, so you can feedback that force into the PTO block. If you have the Simscape Library it will be relatively easy to do this, because there is a block called “Rack & Pinion” that will do exactly what you want. You can also add the inertia block and any other elements of your PTO system (see figure below). I am including a Simulink file with an example for the implementation, remember that this is just an example and you will need to change the system properties to represent your own system.

![image](https://github.com/user-attachments/assets/2c4dacca-7946-444d-b316-68b341586202)

[RM3_LinearToRotary_PTO.zip](https://github.com/user-attachments/files/16911251/RM3_LinearToRotary_PTO.zip)

**Comment by laucrom** [comment]
Hello @jleonqu, thank you for your reply!
I do have the Simscape library available and had tried the method you propose before, but I had not realized that I had to convert the response signal to a force signal for the rack and pinion block to work. Based on the example you showed, it works perfectly now. Thank you so much for the clear explanation!
