### ISSUE TITLE
[BUG?!] Combine h5 files bemio fuction

### ISSUE THREAD

**Issue by ThommyBee** [WEC-Sim/WEC-Sim#150]
Hi all,

just wanted to report a small bug in the BEMIO functions which at least popped up for me:
The "combine_BEM.m" script tries to evaluate the existence of hydro structure fields of the scattering magnitude using the variable F: "isfield(hydro(F),'sc_ma')"

F is not initialized/defined in the combine_BEM function and thus

1) F has to be defined in the combine_BEM function in the same way as being done in the read functions:
```
[a,b] = size(hydro); 
if b==1
    if isfield(hydro(b),'Nb')==0  F = 1;
    else  F = 2;
    end
elseif b>1  F = b+1;
end
```

or

2) F has to be defined as a global variable in all BEMIO read (aqwa, wamit, nemoh) and the combine_BEM function
`global F`

Could someone double check? I'm using the latest version 2.1 of wecSim.

Thanks
TBoerner

**Comment by j-vanrij** [comment]
Thank you for the comment, and I apologize for the slow response. 

So, as BEMIO is written now, Combine_BEM is only utilized if multiple BEM outputs need to be combined into one .h5 output file. There is no reason to run Combine_BEM if there is only one BEM output file.

If there are multiple BEM output files, and Combine_BEM is used, then it is expected that all of the BEM output files either will, or will not, have scattering and Froude-Krylov force data. This is on par with the requirements that each of the BEM outputs have the same water depth, wave frequencies, and wave headings. However, it is true, that this has not been explicitly stated in the description of the Combine_BEM function, and this should be corrected.

Unless, BEMIO is changed first… The scattering and Froude-Krylov variables were not written as global variables since not all BEM output have these data (e.g. WAMIT 6 and earlier, or if IOPTN(3)  was not selected). And, if nonexistent values were saved as zeros, this could be confusing/misleading. However, after discussing this with the WEC-Sim team, I think we are going to modify BEMIO so that the scattering and Froude-Krylov variables are written as global variables (as you have suggested); and if these data are unavailable, the values will be reported as ‘NaN,’ or the like, so as to avoid confusion. I think this approach will cause the fewest mishaps when running BEMIO; but can make no promises as to when this will occur.
