### ISSUE TITLE
Force  relation

### ISSUE THREAD

**Issue by stevenshine** [WEC-Sim/WEC-Sim#156]
Using wecsim softwave, set H=0.5  T=125s
there are wired condition
when forceExcitation is small and then the mooring force is biger
this is normal condition?
or this is out of calculate range ? 
what does wecSim calculate range
 both of force are relate to  equations ,right?
ths u 

(blue))Ex= Excitation
(red)Fm=Mooring

![image](https://cloud.githubusercontent.com/assets/23226663/22634333/a91e70da-ec63-11e6-9117-6d1a6a13f8da.png)
![image](https://cloud.githubusercontent.com/assets/23226663/22634339/b5dd4404-ec63-11e6-97c1-1d2790df621f.png)

**Comment by kmruehl** [comment]
In order to help understand these results, I'll need to know some more information about your model setup and BEM solution. 

1. What is the frequency range of your BEM solution, and what does the solution look like around T=125s? A wave period of 125s is very long and possibly out of the stable range of your BEM solution. 
2. How is the mooring force defined? If it's a stiffness, then the mooing force will be dependent on the WEC displacement.

**Comment by kmruehl** [comment]
@stevenshine does this answer your question?

**Comment by stevenshine** [comment]
@kmruehl 
Maybe, this is out of calculate range. 
the BEM calculate by NEMOH.
BTW 
what do  effect of one-Order Hydrodynamics and effect of Second-Order Hydrodynamics  influences
?
are there about second-Order Hydrodynamics Program language source?
ths u

**Comment by kmruehl** [comment]
I agree, my guess is that the the wave period of 125s is outside of the range of your stable BEM solution. 

The non-linear affects are detailed [on the wec-sim website here](http://wec-sim.github.io/WEC-Sim/features.html#non-linear-hydrodynamics). They include non-linear hydrostatic and non-linear Froude-Krylov forces based on the wetted surface of the STL mesh. Implementation can be found in the bodyClass and within the Simulink body block.
