### ISSUE TITLE
error in tutorial

### ISSUE THREAD

**Issue by ialci** [WEC-Sim/WEC-Sim#210]
![image](https://user-images.githubusercontent.com/32762446/32385188-9a6e0c60-c0bd-11e7-9082-51e06b079863.png)
Hello!
I am new to Wec-Sim and while following the tutorioal Two-Body Point Absorber (RM3) I get the error in the picture above. Could you please help me to solve it?

Specifications:
Windows 10 x64
Matlab and Simulink R2017b 64bit

Thank you very much! :) 
(sorry if it is a silly question)

**Comment by kmruehl** [comment]
@ialci The Matlab error you received is because the `*.h5` files were not downloaded properly. They are stored by GitHub using Git Large File Storage (git-lfs), so you'll need to follow the [git-lfs instructions in the note here](http://wec-sim.github.io/WEC-Sim/getting_started.html#option-3-static-code-download-not-recommended).
