### ISSUE TITLE
Floating Body Initial Orientation

### ISSUE THREAD

**Issue by jdsemrau** [WEC-Sim/WEC-Sim#260]
I'm working with WEC-Sim to model the Orion Crew Module Uprighting System (CMUS). Playing around with WEC-Sim I can get it to model a free floating CM in an upright position (stable 1). For upcoming analysis we'll need to initial the CM upside down (stable 2) or on its side (stable 3). 

I've been poking around in WEC-Sim to see how I can do this, but haven't had any luck. My impression is the mechanism to do this is in the constraint class. I've tried called some of the methods in the constraint class (SetOrientation, setInitDisp, etc) in wecSimInput.py for my setup as best as I can figure to start in stable 2 (180 deg rotation about Y), but no luck. 

Attached is a snip of my setup in stable 1. 

![stable1](https://user-images.githubusercontent.com/41649273/43162351-5bf1dd10-8f50-11e8-805b-a63603bc8a01.PNG)

**Comment by kmruehl** [comment]
@jdsemrau thanks for your questions. It sounds like what you want to do is rotate the CMUS 180deg upside down (stable 2), and 90deg on its side (stable 3). Since it is the body that you want to rotate (not the constraint), this is done within the body class in the `setInitDisp` method. An example of how to use this method is demonstrated in the [IEA_OES_Task10_freeDecay](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/master/IEA_OES_Task10_freeDecay) application case, and documented [here](http://wec-sim.github.io/WEC-Sim/advanced_features.html#decay-tests). Keep in mind that you will need to specify the axis about which the CMUS is rotating, and its angle of rotation.
