### ISSUE TITLE
Problems with electrical power

### ISSUE THREAD

**Issue by balboaf** [WEC-Sim/WEC-Sim#274]
Hello,
I am working on my grade memory about the WECs.
I managed to execute the wecSim code, but I think I have an error in the process, since the graphics obtained do not match the reality. I understand that the electrical power should have a sinusoidal behavior.
![image](https://user-images.githubusercontent.com/34801789/47367115-68c58580-d6b5-11e8-865e-26d5821bf817.png)

I would greatly appreciate it if you could help me.

I attach the files
[WECWR.zip](https://github.com/WEC-Sim/WEC-Sim/files/2506520/WECWR.zip)

**Comment by kmruehl** [comment]
@balboaf since you're running a modified version of the WEC-Sim OSWEC simulation with the hydraulic PTO, the electrical power should not be sinusoidal. The hydraulic PTO system includes high and lower pressure accumulators, which store energy and smooth power. The absorbed power will be periodic with the incident wave, but mechanical and electrical power are smoothed by the accumulator storage. For more info, refer to http://wec-sim.github.io/WEC-Sim/advanced_features.html#tutorial-rm3-with-pto-sim.
