### ISSUE TITLE
Running wecSimMCR

### ISSUE THREAD

**Issue by adetosoafonja** [WEC-Sim/WEC-Sim#284]
I am trying to run a wecSim MCR by just using a range of waves.T. Meaning I do not have to create any external file. e.g I simply did waves.T=0.7:-0.5:0.5 and I run wecSimMCR.
However, I got this error:
```

Error in waveClass/waveSetup (line 251)
                        obj.w = 2*pi/obj.T;

Error in wecSim (line 117)
waves.waveSetup(body(1).hydroData.simulation_parameters.w, body(1).hydroData.simulation_parameters.water_depth, simu.rampTime, simu.dt, simu.maxIt, simu.g, simu.endTime);

Error in wecSimMCR (line 79)
    wecSim;

```
I really need help to figure out what is going wrong

**Comment by kmruehl** [comment]
@adetosoafonja I just ran a wecSimMCR case in the same way and was unable to reproduce this error. Can you upload your case directory so that I see reproduce your error? Thank you.

**Comment by adetosoafonja** [comment]
please find attached case files
[FloaterWEC.zip](https://github.com/WEC-Sim/WEC-Sim/files/2762705/FloaterWEC.zip)

**Comment by kmruehl** [comment]
@adetosoafonja thank you for uploading your case directory. I've attached my edits to your wecSimMCR files that resolve your issue. The issue the `clc; clear all;` at the top of the input file. This makes wecSim crash because there are several variables that are read and saved to the workspace before the wecSimInputFile is read, and they cannot be cleared before a run. 

However, I did notice another issue. Your period range, `waves.T = 7:-0.5:0.5` is outside of the range of your BEM solution, so the first wave periods run, but wave periods `waves.T = 1.5:-0.5:0.5` cannot be run without a BEM solution (i.e. hydrodynamic data) for those wave periods. To resolve this issue, I changed your wave period range to `waves.T = 7:-0.5:2; `

[FloaterWEC_KMR.zip](https://github.com/WEC-Sim/WEC-Sim/files/2765522/FloaterWEC_KMR.zip)

**Comment by adetosoafonja** [comment]
Thanks for taking time to go through the case file. I will implement the changes as noted.

**Comment by kmruehl** [comment]
@adetosoafonja based on a brief scan of your implementation, the feedback appears to be done appropriately. 

My only recommendation would be to move the ART onto the top level of the model by creating a custom block similar to the [PTO Actuation Force/Torque blocks](http://wec-sim.github.io/WEC-Sim/code_structure.html#ptos) we provide in WEC-Sim. It looks like you've used a Floating (6DOF) constraint which doesn't a corresponding PTO Actuation Force/Torque block, but you could create your own (using the `Translational PTO Actuation Force` and `Rotational PTO Actuation Torque` block as a template. The reason for moving the ART to the top level is that the `Rigid Body` blocks have a lot of masks/layers that may no longer work when the library link is broken.

**Comment by sricharanvvs** [comment]
![Screenshot (89)](https://user-images.githubusercontent.com/51389362/71262124-f7d73780-2364-11ea-8e8b-38afb8725c6b.png)
Hi,
I am getting this error while running the RM3_MCR
I have entered wecSimMCR in the command window once. That's it.
where am I going wrong?

For my own model, I getting this error. I have enabled this line in the input file simu.reloadH5Data =1 in my model.

![Capture](https://user-images.githubusercontent.com/51389362/71262555-0bcf6900-2366-11ea-91ce-4e1fcd48e38d.JPG)
Can you help to understand where am I going wrong?
--Thanks in advance
.
