### ISSUE TITLE
mass matrix

### ISSUE THREAD

**Issue by siya-jin** [WEC-Sim/WEC-Sim#337]
Hi,
I am looking at an unsymmetrical hinged-raft device which has nondiagnonal elements in the moment inertia. 
It seems that in WEC-Sim the moment inertial can only be given for the diagonal term of Ixx Iyy and Izz. May i ask does WEC-Sim ignore the nondiagnonal elements? How about the nondiagnonal effects of added mass and radiation damping of Ry to X, Y and Z directions...

Thanks a lot

**Comment by dforbush2** [comment]
Hello,
Because WEC-Sim solves body dynamics about the body center of mass, it is convenient to describe mass/inertia as a diagonal matrix in terms of principle inertias about principle axes X, Y and Z that are mutually perpendicular and coincident with the body center of mass.

However, the added mass and radiation damping matrices are 6 x (6*N), where N is the number of bodies included in the boundary element model. These matrices can (and usually do) include off-diagonal terms. 

Hope this helps.

**Comment by siya-jin** [comment]
Hello,

Thanks for your information. Do you mean WEC-Sim do keep the non-diagonal terms of added mass and radiation damping? But referring to the bodyClass.m file, in the 'adjustMassMatrix' function, it seems that only the diagonal items of the added mass are merged into the mass matrix. This makes me confused..
From your experience, will ignoring the non-diagonal items of the inertia for a unsymmetrical body cause a big effect on the response of a unsymmetrical body.

Best wishes
Siya
________________________________

**Comment by dforbush2** [comment]
Hello,

Please see previous issue #161 as it may answer your question in more detail.
