### ISSUE TITLE
How to Calculation More than One Sea-state(e.g.Hs=2.5m, Te=8s)

### ISSUE THREAD

**Issue by duxiao96** [WEC-Sim/WEC-Sim#356]
Thank you,  WEC-Sim team.
 I am trying to do reliability of power semiconductors in WEC using the RM3 model.
my questions are:
1、How to Calculation More than One Sea-state(e.g.Hs=2.5m, Te=8s)?
2 、Where Can I Find Output Power of WEC based on results of simulation ?(Regular Waves，Irregular Waves[Power Output Matrix])

**Comment by dforbush2** [comment]
Hi @duxiao96

1. I would recommend you check out WEC-SimMCR for this task. It allows you to specify a vector of sea-states which WEC-Sim will execute in order.
 https://wec-sim.github.io/WEC-Sim/advanced_features.html#multiple-condition-runs-mcr

There is an Applications example as well as a webinar for this feature, available at the provided link.

2. I would need more information on your particular model to answer this with certainty. If you have follow-up questions, please also attach your model. 

But as an example, the example/RM3 model approximates the PTO as a damper in heave only. The MECHANICAL power absorbed by the PTO is found in: 

output.ptos.powerInternalMechanics(:,3)

 where the third column is taken since the PTO applies to the heave degree of freedom. This is equal to the product of velocity and PTO-applied force: 

output.ptos.velocity(:,3) .* output.ptos.forceInternalMechanics(:,3). 

The forceInternal and powerInternal mechanics fields are taken because the specified damping is calculated inside the PTO block. If you have another force specified as an actuation force (i.e., you are using a block like WEC-Sim/PTOs/Translational PTO Actuation Force), then you would also have to include forceActuation in the latter product to calculate MECHANICAL power.

Given the subject of your investigation, you likely will want to examine ELECTRICAL power. If you are using blocks in PTOSim, then electrical power will output to output.ptosim. If you are using a custom PTO implementation, then I would recommend directly specifying your electrical power using a "To Workspace" block in simulink. 



However, if you are using your own custom PTO block, you can specify an output

**Comment by duxiao96** [comment]
Thanks you very much.
Based on PTOsim, I also have some question.
1、The ElecPower is too small, several hundred watts.(regular Hs=2.5m,Te=8s)
2、the Phase A current is also small
However, I don't know where the simulation model is wrong or other problems.













At 2020-06-04 03:36:23, "dforbush2" <notifications@github.com> wrote:

Hi @duxiao96

I would recommend you check out WEC-SimMCR for this task. It allows you to specify a vector of sea-states which WEC-Sim will execute in order.
https://wec-sim.github.io/WEC-Sim/advanced_features.html#multiple-condition-runs-mcr

There is an Applications example as well as a webinar for this feature, available at the provided link.

I would need more information on your particular model to answer this with certainty. If you have follow-up questions, please also attach your model.

But as an example, the example/RM3 model approximates the PTO as a damper in heave only. The MECHANICAL power absorbed by the PTO is found in:

output.ptos.powerInternalMechanics(:,3)

where the third column is taken since the PTO applies to the heave degree of freedom. This is equal to the product of velocity and PTO-applied force:

output.ptos.velocity(:,3) .* output.ptos.forceInternalMechanics(:,3).

The forceInternal and powerInternal mechanics fields are taken because the specified damping is calculated inside the PTO block. If you have another force specified as an actuation force (i.e., you are using a block like WEC-Sim/PTOs/Translational PTO Actuation Force), then you would also have to include forceActuation in the latter product to calculate MECHANICAL power.

Given the subject of your investigation, you likely will want to examine ELECTRICAL power. If you are using blocks in PTOSim, then electrical power will output to output.ptosim. If you are using a custom PTO implementation, then I would recommend directly specifying your electrical power using a "To Workspace" block in simulink.

However, if you are using your own custom PTO block, you can specify an output

**Comment by duxiao96** [comment]
Sorry, I do not know how to I don't know how to attach the file.
Can I send it to your mailbox?
At the same time, the reply mail last time has a model.

**Comment by dforbush2** [comment]
Hi @duxiao96 

You should be able to attach a file by dragging/dropping into the comment box on git. But if you are talking about the unmodified PTO-Sim/RM3_DD_PTO example in the WEC-Sim Applications repository I can see this model already. 

Looking through the model, everything seems to be in order. An electrical output of several hundred watts does not seem unexpected. Parameters involved in that calculation can be varied within the `ptoSimInputFile.m` if you'd like to investigate other combinations. I would also try sea states with a different energy period if you would like to see higher values.

I would recommend using the Fourier transform on your fully-developed output data to get voltage or frequency content. Relevant output data is in output.ptosim.pmLinearGenerator. If needed (for example) for a control system it is also possible, albeit more challenging, to do this in "real-time" within the model. I highly recommend writing your own blocks to do this, but there are some pre-made options available in Simscape Electrical and DSP toolboxes.

**Comment by kmruehl** [comment]
@duxiao96 does this resolve your issue?

**Comment by duxiao96** [comment]
thank you very much!
