### ISSUE TITLE
wave direction

### ISSUE THREAD

**Issue by siya-jin** [WEC-Sim/WEC-Sim#386]
Hi there,
I am confused with the wave direction setting in WEC-Sim
I generated the hydrodynamic coefficients from AQWA. In the setting, three wave directions have been considered: -180, 0 and 180 degree. I felt confused with the .h5 hydroData generated from BEMIO. Under the hydroData, wave_dir, three directions have been read. I am wondering do I need to specify the wave direction like waves.waveDir =0 in the 'wecSimInputFile.m'? if not, will the WEC-Sim calculate the results for wave direction of -180 degree?
Thanks.
PS, I went through the .AHI and .LIS file published by you in the GitHub. In the files, only output the wave directions in negative (-180, -135, -90, -45, 0). How did you format the output data like this? without the data of 45, 90, 135 and 180 degree? When I output the hydrodynamic data, it generate the results from -180 to 180..

**Comment by kmruehl** [comment]
@siya-jin since you ran AQWA for -180, 0 and 180 degrees, the hydrodynamic data for those wave directions should be included in the `*.h5` file generated from BEMIO. If you want to run WEC-Sim for a wave direction other than 0 degrees you will need to specify `waves.waveDir` in the `wecSimInputFile.m`. The default value of  `waves.waveDir = 0`, refer to [API documentation here ](http://wec-sim.github.io/WEC-Sim/api.html#source.objects.waveClass.waveDir).

Regarding the wave directions output to the `*.LIS` and `*.AH1` from AQWA, that's an AQWA input parameter. You can manually specify the wave directions you would like to run.

**Comment by kmruehl** [comment]
@siya-jin did this resolve your issue?

**Comment by siya-jin** [comment]
________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.
