### ISSUE TITLE
A question about PTO-Sim

### ISSUE THREAD

**Issue by qorbanpour** [WEC-Sim/WEC-Sim#431]
I am new to WEC-Sim and I was reading the tutorial about PTO-Sim  :  

https://wec-sim.github.io/WEC-Sim/advanced_features.html#pto-sim

In the tutorial it is mentioned as follow : 

```
In summary, the files need to run RM3 with PTO-Sim case are the following:
WEC-Sim input file: wecSimInputFile.m (make sure to set the PTO linear damping to zero)
```

My question is :

Why the damping should be set to zero ( my guess is that it's calculated in PTO-Sim block somewhere ) . Also Is the stiffness from PTO block needs to be set to zero ! 

Or better putting in this way,  Having a PTO-Sim block , what is the role of stiffness and damping from PTO-block , considering that all PTO-Sim blocks that comes with WEC-Sim example are hydraulic or  Direct Drive PTO  !  

Warmest Regards,
Sahand.

**Comment by dforbush2** [comment]
Hi @qorbanpour 

"Why the damping should be set to zero (my guess is that it's calculated in PTO-Sim block somewhere )"

Your guess is correct! When using PTO-Sim blocks, these parameters (k and c) are functions of the specific PTO component parameters (e.g., motor constants and friction, etc). The k or c specified in the simple ptoClass blocks (pto.k and pto.c) are not used by the PTO-Sim blocks, and are external to them. You could (I suppose) use the pto.k and pto.c to account for some sources of stiffness external to the system described in PTO-Sim, but in the example you are discussing, there were no external stiffness and damping terms, and so pto.k = 0 and pto.c = 0.  

Be aware this extends to calculated quantities like power: the power calculated in the ptoClass block will, in this example, be zero, but the power in the hydraulic or direct-drive PTO, which represents the power used/absorbed by the device, is non-zero.  

I understand how this can be confusing: we are revising our documentation to better address this.

Does this answer your question?

Best,
Dom

**Comment by jleonqu** [comment]
Hi @qorbanpour 

In the example that you mentioned the hydraulic PTO is used. The hydraulic PTO is receiving an input from the Translational PTO Actuation Force. If you take a look inside this block, you can see that there is a subsystem called InternalMechanics.

![image](https://user-images.githubusercontent.com/72461917/97329317-8990ba80-183c-11eb-9252-d47456db6a32.png)

This subsystem is versatile and you can use it depending on your specific needs. As default, the subsystem is solving the dynamic equation for a translational PTO mechanism represented as a linear spring-damper system, which is:

F_pto = -K_pto*x_rel - C_pto*v_rel

This equation can change depending on the characteristics of the systems that you want to simulate. This can be used to simulate, for example, the energy loss by friction in the mechanical connection of the PTO or it can be used to simulate your own model for a new PTO system. In the specific case of the example with the hydraulic PTO, the damping and the stiffness are zero because otherwise it would be like if you were using two PTO systems at the same time.

I hope this can help you with your simulation.

Best,

Jorge Leon

**Comment by kmruehl** [comment]
@qorbanpour Does this answer your question?

**Comment by qorbanpour** [comment]
@dforbush2  Thank you for the explanation . 
@jleonqu  Thank you for the nice explanation .
@kmruehl  Yes, it helped alot . Thanks for clarification and your helps .

Warmest,
Sahand.

**Comment by kmruehl** [comment]
Of course, I'm going to close this issue.
