### ISSUE TITLE
Error while using FreeDecay test for multibody case

### ISSUE THREAD

**Issue by BinoBK** [WEC-Sim/WEC-Sim#502]
Dear WEC-Sim team,
I am trying to run runFreeDecay.m code for a multibody case, which is the WECCCOMP model with the PTO block removed. There are 5 bodies in the model: Float, Arm, BC, Frame and Motor. 

But I am getting following error:

***************************************************************
Expected one output from a curly brace or dot indexing expression, but there were 5 results.
Error in plotFreeDecay (line 11)
    plot(output.bodies.time,output.bodies.position(:,3)-body(1).cg(3))

Error in runFreeDecay (line 13)
plotFreeDecay
***************************************************************
I am using the latest WEC-Sim code and running it on Matlab R2020b. I also made sure that the directory path is correct. I have attached the zipped file below. 

[1 FreeDecay_WECCCOMP.zip](https://github.com/WEC-Sim/WEC-Sim/files/5850967/1.FreeDecay_WECCCOMP.zip)

Kindly extend support to resolve above error. 

Thanks,
Bino

**Comment by akeeste** [comment]
Hi @BinoBK 

The plotting function is giving you an error because it is trying to read multiple bodies at the same time. In the original free decay example 'output.bodies' gives 1 result. However in the WECCCOMP case, this gives an array of 5 bodies. 

Instead use: 
plot(output.bodies(1).time,output.bodies(1).position(:,3)-body(1).cg(3))

Please take time to debug carefully before submitting an issue. Some care is needed when combining examples as the plotting scripts may need to be adapted to a new case.
