### ISSUE TITLE
Questions about Hydraulic PTO

### ISSUE THREAD

**Issue by rodrijardim** [WEC-Sim/WEC-Sim#556]
Hello everyone,

I am testing the RM3 hydraulic model with compressible fluid provided by the program but I have some questions about the accumulator variables in the "ptoSimInputFile.m" file.

**1) What is the purpose of the "accumulator" variables found in the image below:**
![image](https://user-images.githubusercontent.com/80351501/114316887-75e0c400-9afd-11eb-9e20-43fe40a1f429.png)

**1a) Why do both equivalent accumulator pressures (pIeq) have the same value if both have different initial volumes, pIprecharge and VIeq?**

"ptosim.accumulator (1) .pIeq = ptosim.accumulator (2) .pIeq;"

"ptosim.accumulator (2) .pIeq = ptosim.accumulator (2) .pIprecharge / (1-ptosim.accumulator (2) .VIeq / ptosim.accumulator (2) .VI0) ^ (1.4);"

**1b) Why is the volume of liquid equivalent (VIeq) in the accumulators calculated differently?**

"ptosim.accumulator (1) .VIeq = ptosim.accumulator (1) .VI0 * (1- (ptosim.accumulator (1) .pIprecharge / ptosim.accumulator (1) .pIeq) ^ (1 / 1.4));"

"ptosim.accumulator (2) .VIeq = ptosim.accumulator (2) .VImax;"

**1c) What is the variable del_p_r for? "ptosim.accumulator (1) .del_p_r"**

**2) I started to simulate the program with the data already defined and got the following genTorque and angular velocity response:**

![image](https://user-images.githubusercontent.com/80351501/114316990-e12a9600-9afd-11eb-8765-d8dbd35f0d62.png)

I wanted to smooth out the genTorque response (less sinusoidal amplitude) but I don't know what parameters I should change in the "ptoSimInputFile.m" file since genTorque is dependent on the "delPress" and "motorVol" variables.
![image](https://user-images.githubusercontent.com/80351501/114317077-42526980-9afe-11eb-8d9c-8dfc82b393b4.png)

Any suggestion?
Thank you

**Comment by jleonqu** [comment]
Hello @rodrijardim 

1) ptosim.accumulator(2).VIeq is the initial value for the instantaneous volume of the accumulator. You can find that variable in the initial condition of the integrator shown in this figure:
![image](https://user-images.githubusercontent.com/72461917/115181223-acd24f00-a094-11eb-8a02-b3a399cfe529.png)

Ptosim.accumulator(2).pIeq is the initial value of the instantaneous pressure in the hydraulic accumulator.

1a) You can find the hydraulic system simulated in the RM3 example in figure 4 in this reference:

https://tethys-engineering.pnnl.gov/publications/development-pto-sim-power-performance-module-open-source-wave-energy-converter-code

The speed of the hydraulic motor is zero in the initial condition, and there is no other external torque acting as a brake, so the pressure in both accumulators should be the same at the beginning of the simulation.

1b) VIeq is the initial volume of the accumulator. The initial volume in the low pressure accumulator is equal to VImax as you mentioned in your question, but VImax is calculated in line 28 in the ptoSimInputFile. From that equation it is possible to see that the pressure used to calculate the volume is the upper limit pressure in the accumulator, so the low pressure accumulator is full at the beginning of the simulation.  You can double check this with the values of ptosim.accumulator(2).pIeq and ptosim.accumulator(2).pIupper_limit

The initial volume in the high pressure accumulator is calculated in line 43 of the ptoSimInputFile. The initial pressure in this accumulator is less than the upper limit pressure, so this accumulator is not at its full capacity at the beginning of the simulation. The same model is used to calculate the initial volume in both accumulators.

1c) The variable ptosim.accumulator (1) .del_p_r is the pressure difference in the rated pressure for the accumulators, this variable can be changed according to the specific characteristics of the system.

2) I would try to change the characteristics of the accumulator like the maximum volume, the precharge pressure, and the maximum pressure, because the stiffness of the accumulator and the hydraulic system depends on these variables. You can also try to add a dissipation term in your model of the hydraulic motor. I think that could smooth out the torque output.
