### ISSUE TITLE
[BUG] Matlab R2021b body mask issue?

### ISSUE THREAD

**Issue by t-osu** [WEC-Sim/WEC-Sim#758]
Hey all,

**Describe the bug**
Possible bug. I just updated to Matlab's latest release R2021b and have tried my personal wec-sim models that were working earlier this week and end up with a consistent error:

```
Error using wecSim (line 375)
Error due to multiple causes.
Caused by:
    Error using wecSim (line 375)
    Error in 'standalone/Hull1/Hydrodynamic Body': Failed to evaluate mask initialization commands.
        Error using wecSim (line 375)
        File Solid block (mask) does not have a parameter named 'ExtGeomFileType'
    Error using wecSim (line 375)
    Error in 'standalone/Pendulum/Non-Hydro Body': Failed to evaluate mask initialization commands.
        Error using wecSim (line 375)
        File Solid block (mask) does not have a parameter named 'ExtGeomFileType'
```

I tried rebuilding the model and the error occurs when renaming a body block to body(2).

**WEC-Sim file(s)**
I was able to reproduce this with the RM3 example file when trying to rename.

**To Reproduce**
_Steps to reproduce the behavior:_
Open RM3 example and rename Spar/Plate to body(3), then rename back to body(2) and the error pops up.

**Expected behavior**
A successful rename.

**Screenshots**
Error in simulink shown for RM3. 
![bpdy error](https://user-images.githubusercontent.com/68524876/139154632-6b674a56-912d-466d-bf9b-408500259172.PNG)

**Workstation Information (this section MUST BE completed):**
 - OS: Windows 10
 - MATLAB Version: 9.11.0.1769968 (R2021b)
 - wecsim v4.2

**Additional context**
N/A

Thanks for any help. I can move it to a different label if this isn't considered a bug.

- Chris

**Comment by Fredoom8** [comment]
Hi @akeeste, I read your explanation and the one in #546, and this is what I understand: the operation to avoid this error is a higher version of WecSim and matlab R2021a or less, i.e., satisfy both WecSim version >= 4.2 and matlab < R2021a, right? Because I am using WecSim version 6.0 and matlab R2024a, when I simulate to the last step of the visualization screen, I get the same error as #546, but since I am not a programmer by profession, I understand your explanation of the cause of this error in #546, and I would like to know if there is a way to run this program without changing the version of wecSim and matlab, without changing the version of wecSim and matlab? I would like to know if there is any way to run this program without changing the version of wecsim and matlab? Can you describe it in detail.
