### ISSUE TITLE
OSWEC Tutorial Moment of Inertia tensor inconsistency

### ISSUE THREAD

**Issue by hresing** [WEC-Sim/WEC-Sim#890]
In the OSWEC tutorial documentation, the moment of inertia is written as
![image](https://user-images.githubusercontent.com/97714842/174879583-5e835337-0b5b-45fd-9698-ffc77efbd885.png)
I would think that this moment of inertia should be about the y axis given that the y axis is the pitch axis in WEC-Sim.
In addition, in the tutorial wecSimInput File, the moment of inertia is written as
body(1).inertia = [1.85e6 1.85e6 1.85e6];  % Moment of Inertia [kg-m^2]
with all three of the directions as equal. 

Is this intentional, or is this a typo in both places as it seems to be?

Also, has there been a change in the notation of moment of inertia of a body in the code? I have been using my downloaded version (and downloaded tutorial input file) with body(i).momOfInertia, but the documentation I am looking at now simply uses body(i).inertia.

**Personal project context**
I am trying to model a similar OSWEC and thought that the tutorial could be a good point of reference.

**Comment by dforbush2** [comment]
Hi @hresing 

I agree this is confusing in the documentation, and should refer to the y-axis (since +x is the default direction of wave propagation). With respect to the model, because the device is only free to oscillate about the y axis, the inertia vector

body(1).inertia = [1.85e6 1.85e6 1.85e6]; % Moment of Inertia [kg-m^2]

Only uses the second element (referring to moment about y) to calculate device dynamics.

**Comment by jtgrasb** [comment]
Hi @hresing, @dforbush2,

I created PR #894 to address this issue. 

Also, the reason you are seeing a difference in notation for the inertia is likely because you downloaded WEC-Sim before our [V5.0 release](https://github.com/WEC-Sim/WEC-Sim/releases), which refactored many variable names. We recommend users to clone the GitHub repository in order to easily pull new updates such as our V5.0 release.
