### ISSUE TITLE
Purpose of transport delays in hydro bodies? Buffer size

### ISSUE THREAD

**Issue by t-osu** [WEC-Sim/WEC-Sim#909]
**Cite the [WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications) case in question**
_Hydrodynamic body --> transport delay._

**Describe the bug or issue**
_I'm running a simulation and have had the simulation stuck solving; there's no error, but there's no progress and it stays essentially frozen. It is due to the buffer size of the transport delays in the hydrodynamic body after "FROM acc" and again in the morison element and viscous damping force calculation acceleration input. Matlab states that the buffer size temporarily increases in an attempt to further the simulation, but it looks like this isn't helping. To try and better understand this, what are the purposes of these transport blocks (shown in screenshot)? Why do we want to delay the input to the B2B and morison element subsystems?_

**To Reproduce**
_Steps to reproduce the behavior:_

_I believe this is model specific and am unsure if sharing is allowed._

**Expected behavior**
_The model to run._

**Screenshots**
_Attached_
![transport delay](https://user-images.githubusercontent.com/68524876/178373227-40de693b-b427-4383-94e1-2e21413896ff.PNG)
![transport delay2](https://user-images.githubusercontent.com/68524876/178373230-15419283-fcc9-4594-bc46-1b44a572f9aa.PNG)
_From command line:
`Warning: The specified buffer for 'Dizon_asbuiltmod_wecup/Rigid Body2/Hydrodynamic Body/Transport Delay' was too small. During simulation, the buffer size was
temporarily increased to 11264. In order to generate code, you need to update the buffer size parameter `_

**Workstation Information (this section MUST BE completed):**
 - OS: microsoft windows 10 enterprise
 - [MATLAB/Simulink Release] 2022a
 - [WEC-Sim Release] v5.0

**Additional context**
_Upon double clicking on the transport delay you can change the buffer size, but it looks like with v5.0 you can no longer break the library link to make edits within the blocks? Unsure if this would actually solve the problem since Matlab auto increases the size, just another comment. I also tried increasing their original sample time from 0.001s to 0.01...0.1...with the same result.
Thanks for any input!_

**Comment by dforbush2** [comment]
Hi @t-osu 

The transport delay block is there to avoid an algebraic loop in the force due to added mass calculation. If it is causing some problems, you could swap it out for another method:
https://www.mathworks.com/help/simulink/ug/remove-algebraic-loops.html 

The "best" option is generally to use a transfer function block to make a low pass filter with a break frequency a fair bit above the highest frequency dynamic that is of interest. 

To do this, you'll have to break the link and modify the block. You ought to be able to do this by:
1) Open the simulink library (you can get there from right clicking the Lock Link logo in the lower left of you model and selecting "go to library block").
2) Unlock the library (Library tab, big lock icon)
3) Unlock the links (Library tab, smaller lock icon immediately to the right of the lock in 2)).
4). Open the model you want to modify and make the changes. 

You should now be able to modify your model as you need without messing with the WEC-Sim library. Of course, if you modify the library block it will work too, but this change will then appear in all your models that call this library.
