### ISSUE TITLE
[Theory or Implementation] Handling Nonlinear and Linear Forces

### ISSUE THREAD

**Issue by Dadidal** [WEC-Sim/WEC-Sim#988]
**Is your question request related to a problem? Please describe.**
I do not understand the combination rule for Linear wave excitation force and Froude-Krylov (FK) forces. Also, I want to clarify the correct way to account for first-order, second-order, and other nonlinear forces simultaneously.

**Describe the theory or implementation approach that you have a question**
1. In WEC-Sim documentation there is the following text:
`Rather than using the BEM calculated linear wave-excitation and hydrostatic coefficients, the nonlinear buoyancy and the Froude-Krylov force components can be obtained by integrating the static and dynamic pressures over each panel along the wetted body surface at each time step.`
But if we look under the mask of Hydrodynamic body/Wave Diffraction and Excitation Force Calculation blocks we will see the summation of Linear Excitation and Nonlinear FK Force. I understand that If simu.nlHydro == 0 the FK Force will be zero. But am I correct that if simu.nlHydro == 1 or 2 the FK forces will be added to Linear forces?
![image](https://user-images.githubusercontent.com/32517441/216264685-2b67ebf9-ab89-45e6-a45c-122c535d1d92.png)

2. I understand that total excitation force consists of diffraction and FK forces. Can WEC-Sim handle these two components separately? If nonlinear FK forces are used the linear FK forces must be excluded. But if we look under the block "Hydrodynamic Body/Wave Diffraction and Excitation Force Calculation/Linear Wave Excitation Force Variant Subsystem/Regular Wave Excitation Force", we can see only body.hydroForce.fExt.re(1,:) term. I use BEM data from NEMOH. How BEMIO convert diffraction and FK coefficients to F_exc(w, omega) used by WEC-Sim [https://wec-sim.github.io/WEC-Sim/master/theory/theory.html#sinusoidal-steady-state-response](url)?
![image](https://user-images.githubusercontent.com/32517441/216267870-3e8c5989-e95d-4467-a6a4-132760517ca3.png)

3. Also, I want to clarify about mean drift forces. I can calculate the mean drift force from AQWA. Is it the Fmd(w, omega) coefficients that are mentioned in the WEC-Sim documentation? Am I correct that this force is different from diffraction and FK force and can be added to make the simulation more precise even in the case of nonlinear calculation of FK forces? 

4. About nonlinear viscous damping Fv [https://wec-sim.github.io/WEC-Sim/master/theory/theory.html#viscous-damping](url).
If I use C_v and C_D coefficients I have to define a 6x6 matrix, right? What velocities are then used to determine these forces in the rotational degrees of freedom (pitch, roll, yaw) - translational or angular velocities? Can I model yaw rate drag using this option? [https://www.orcina.com/webhelp/OrcaFlex/Content/html/Vesseltheory,Currentandwindloads.htm#VesselTheoryYawRateDrag](url)

5. Can WEC-Sim account for Manoeuvring load? [https://www.orcina.com/webhelp/OrcaFlex/Content/html/Vesseltheory,Manoeuvringload.htm](url)

**Personal project context**
**Describe the type of conclusion or resolution you are looking for**
I want to do as much accurate implementation as possible.
1. Now I use simu.nlHydro == 1 but I don't understand if is there a double count of the contribution from Wave excitation forces (diffraction and FK)?
2. Also, I want to clarify about the meaning of mean drift forces - do they differ from wave excitation forces?
3. Can I add mean drift forces in the case of a one-directional regular wave (waveClass('regularCIC')) or if it doesn't make sense?
4. What velocity terms are used in the implementation of viscous forces - translational or angular velocities?
5. Can WEC-Sim account for Manoeuvring load?

Also here I attach the AQWA 2022 R2 and NEMOH 3.0.1 calculations for the same structure. They contain Separate diffraction coefficients, FK coefficients as well as mean drift forces (AQWA)
[BEM.zip](https://github.com/WEC-Sim/WEC-Sim/files/10567094/BEM.zip)

**Comment by dforbush2** [comment]
Hi @Dadidal 

There are a lot of questions here! To aid future users in tracking down this information, I'm going to split this over multiple issues. I'll answer 1, 2 and 3 here, since they are all related to Froude-Krylov force calculations, but I will open a new issue to address 4 and 5 and tag you in these issues. 

1) Yes, the linear excitation forces appear to be added to the Froude-Krylov forces in the simulink implementation, but if we look at the function that is used to calculate the Froude-Krylov force 'nonFKForce', the output is actually _just_ the non-linear FK components (specifically see line 41). In this way, we are not double-counting the linear Froude-Krylov components. 

2) I'm not sure I understand this question. The frequency domain excitation coefficients output from a BEM solver like NEMOH are already in the necessary form: F_exc(w, omega), a coefficient relating complex wave height to complex excitation force as a function of wave direction and frequency, these include _linear_ Froude-Krylov, Diffraction, and Scattering components of the excitation force, but the way these are reported out varies with the particular BEM software: they are combined appropriately into F_exc(w,omega) in the BEMIO functions. In Simulink, F_exc(w,omega) is scaled appropriately and present as the coefficients called fExt.re and fExt.im that are utilized in "Hydrodynamic Body/Wave Diffraction and Excitation Force Calculation/Linear Wave Excitation Force Variant Subsystem/Regular Wave Excitation Force". 

fExt,md is the "mean drift" force. This is intended to model a device that is subjected to both waves and currents: i.e., a device in a wave field and also a 1 m/s flow field. The fExt.md component of this force is non-zero only in the case where the mean flow is non-zero: in just a wave field, fExt.md = 0. 

3) Based on above, if it is just a wave field with no mean flow, fExt.md = 0, so trying to include them does not make sense. Adding fExt.md will only improve accuracy for simulations where there is a non-zero mean flow.

**Comment by dforbush2** [comment]
@Dadial please see also #995

**Comment by Dadidal** [comment]
@dforbush2 Thank you for the detailed explanation. Now I understand how WEC-Sim accounts for Linear and Nonlinear parts. 

But now it seems that some correction to documentation is needed. Here I refer to the following text again from the documentation:
`Rather than using the BEM calculated linear wave-excitation and hydrostatic coefficients, the nonlinear buoyancy and the Froude-Krylov force components can be obtained by integrating the static and dynamic pressures over each panel along the wetted body surface at each time step.`
The formulation "Rather..." is not correct here because WEC-Sim still uses BEM coefficients to calculate the linear term of FK forces.

Regarding the Nonlinear term now I understand the "nonFKForce" function subtracts the linear part from the full FK force (line 41) and the result is JUST the "additional to linear" term. But here I also see the problem. To be consistent, the linear forces from the BEM coefficients and the linear forces calculated by the "nonFKForce" function (line 39) must be equal, right? I temporary modified "nonFKForce" function so the output is only linear term:
```
% Calculate forces
f_linear   =FK(centerMeanFS,       cg,avMeanFS,wpMeanFS);
f_nonLinear=FK(center      ,x(1:3)+cg,av      ,wp      );
%f = f_nonLinear-f_linear;
f = f_linear;
```
After that, I did a simulation and checked the output of the "Linear Wave Excitation Force Variant Subsystem" and the "Nonlinear FK Force Variant Subsystem" output. The results are in the figures below. The linear excitation force from BEM and linear FK force from "nonFKForce" function are not equal. 
![Linear Exc](https://user-images.githubusercontent.com/32517441/220527891-b7d8b312-bac3-4da6-a970-a67110eceddf.jpg)
![Nonlinear FK](https://user-images.githubusercontent.com/32517441/220527906-7b9aaec6-135d-40c2-a057-85b474f0664f.jpg)

So now I have a question is it correct or not? Maybe I am wrong because the linear force from BEM includes not only FK force but also the diffraction force. Please clarify this for me.

Thank you in advance.

**Comment by dforbush2** [comment]
Hi @Dadidal 

As you noted in some of your previous questions, the wave diffraction, linear Froude-Krylov, and scattering components are combined in BEMIO to create a single linear Force Excitation coefficient (exactly how depends on the BEM code that is being used and its configuration).

With regard to the test you performed, I would not expect these results to be equal because when using the non-linear Froude Krylov option only the linear Froude-Krylov portion is subtracted and this is only a portion of the forces that are calculated using the force excitation coefficients (because the excitation coefficients additionally include diffraction and scattering).

So informally, the operations look like this:
Non-linear Froude Krylov option:
F_{excitation} = F_{BEM excitation coeffs} + F_{NL function}
F_{BEM excitation coeffs} =  F_{diffraction} + F_{scattering} + F_{linear FK} 
and the non-linear froude Krylov function calculates 
F_{NL function} = (F_{linear FK} + F_{nonlinear FK}) - F_{linear FK})

So in total, the result looks like this:
F_{excitation} = F_{diffraction} + F_{scattering} + F_{linear FK} + F_{nonlinear FK}

Which only differs from the excitation calculated by BEM coefficients (F_{BEM excitation coeffs}) in the inclusion of the F_{nonlinear FK} term.  

There is a possibility that the _linear_ FK components may differ from BEM calculations to the simulink-function based calculation, and this could result in a difference in this term, but this would not be directly checked from simulation results. This is one important reason to use a well-discretized *.stl mesh whenever non-linear hydrodynamics options are used. 

I agree our documentation on this point is unclear: I will fix this today.

@nathanmtom  please let me know if I have any of this wrong.

**Comment by nathanmtom** [comment]
Thanks @dforbush2 for your explanation and I agree with your description above. We have an action card on our project board to update our documentation on the nonlinear hydrostatics and hydrodynamics implementation. 

@Dadidal Do you have any remaining questions related to this issue? We have not heard from you since February and will plan to close this issue at the end of the week if we do not see any action.

**Comment by Dadidal** [comment]
@nathanmtom @dforbush2 Thank you for the explanation, I don't have questions regarding this problem anymore.
